# Generated by Django 4.2.13 on 2024-06-24 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('efficiency', '0002_alter_productionlog_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionlog',
            options={'verbose_name': 'Production Log', 'verbose_name_plural': 'Production Logs'},
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_name',
            field=models.CharField(help_text='Name of the machine', max_length=255),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_serial_no',
            field=models.CharField(help_text='Serial number of the machine', max_length=255),
        ),
        migrations.AlterField(
            model_name='machine',
            name='time',
            field=models.DateTimeField(auto_now=True, help_text='Last updated time'),
        ),
        migrations.AlterField(
            model_name='productionlog',
            name='cycle_no',
            field=models.CharField(help_text='Cycle number of the production log', max_length=255),
        ),
        migrations.AlterField(
            model_name='productionlog',
            name='duration',
            field=models.DurationField(blank=True, help_text='Duration of the production cycle', null=True),
        ),
        migrations.AlterField(
            model_name='productionlog',
            name='end_time',
            field=models.DateTimeField(help_text='End time of the production cycle'),
        ),
        migrations.AlterField(
            model_name='productionlog',
            name='machine',
            field=models.ForeignKey(help_text='Machine associated with the production log', on_delete=django.db.models.deletion.CASCADE, to='efficiency.machine'),
        ),
        migrations.AlterField(
            model_name='productionlog',
            name='material_name',
            field=models.CharField(help_text='Name of the material being processed', max_length=255),
        ),
        migrations.AlterField(
            model_name='productionlog',
            name='start_time',
            field=models.DateTimeField(help_text='Start time of the production cycle'),
        ),
        migrations.AlterField(
            model_name='productionlog',
            name='unique_id',
            field=models.CharField(help_text='Unique identifier of the production log', max_length=255),
        ),
    ]
